version: "3.9"
services:
  db:
    image: postgres:16
    container_name: media_db
    environment:
      POSTGRES_USER: media
      POSTGRES_PASSWORD: media_pw
      POSTGRES_DB: mediarating
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
volumes:
  pgdata:
